### ISSUE TITLE
Blockquote and paragraph tag leaves a big vertical gap

### ISSUE THREAD

**Issue by fasiha** [5ARMALE/retrofulhugo#1]
When I render a regular Markdown quote

> like this

Hugo/Blackjack renders this as `<blockquote><p>like this</p></blockquote>`, which leaves a large gap above the quoted text:

<img width="820" alt="screen shot 2017-05-06 at 18 11 27" src="https://cloud.githubusercontent.com/assets/37649/25776255/71f15b08-3287-11e7-9289-984e7e360164.png">

Is it possible to add a CSS rule for `blockquote p` to make this gap smaller?

**Comment by paskal** [comment]
Sorry for posting in the unrelated issue, I don't want to create new one for such insignificant event: I'm not sure github sent notifications to mentioned authors, so posting double there: theme highlight blog post is out, this very theme is in it, additional info on https://github.com/paskal/terrty/issues/1.
